[settings]
node_spawn_timeout = 120
provider = "native"
timeout = 600

[relaychain]
default_command = "polkadot"
default_args = [ 
        "-lparachain=debug",
        "-lbeefy=debug",
        "--beefy",
        "--enable-offchain-indexing=true"
        ]
chain = "rococo-local"

	[[relaychain.nodes]]
	name = "alice"
    validator = true
	rpc_port = 30444
    ws_port = 9944
    args = [
        # "--unsafe-ws-external",
        # "--unsafe-rpc-external",
        "--rpc-external",
        "--ws-external",
        # "--rpc-methods=Unsafe",
        # "--beefy",
        # "--enable-offchain-indexing=true",
        # "-lbeefy=debug"
        ]

	[[relaychain.nodes]]
	name = "bob"
	validator = true

	[[relaychain.nodes]]
	name = "charlie"
	validator = true

	[[relaychain.nodes]]
	name = "dave"
	validator = true

	[[relaychain.nodes]]
	name = "eve"
	validator = true

[[parachains]]
id = 2222
chain = "statemine-local"
cumulus_based = true

	# run alice as parachain collator
	[[parachains.collators]]
    command = "polkadot-parachain"
    args = [
        "--force-authoring",
        # "--unsafe-ws-external",
        # "--unsafe-rpc-external",
        "--rpc-external",
        "--ws-external",
        # "--rpc-cors=all",
        # "--rpc-methods=Unsafe"
        ]
	name = "Ferdie"
	validator = true
    rpc_port = 32200
    ws_port = 9988
    [[parachains.collators.env]]
    name = "RUST_LOG"
    value = "runtime=debug,parachain=trace,cumulus-collator=trace,aura=trace,xcm=trace"

	# run bob as parachain collator
	[[parachains.collators]]
    command = "polkadot-parachain"
	name = "Boern"
	validator = true
    [[parachains.collators.env]]
    name = "RUST_LOG"
    value = "runtime=debug,parachain=trace,cumulus-collator=trace,aura=trace,xcm=trace"
